### PR TITLE
rename Dapp to Chain

### PR DESCRIPTION
**Pull request by bassjobsen**
rename `dapp` to `chain` and fixed the tests according it

### CODE REVIEW

**Comment by a1300** [comment]
@bassjobsen please provide a short summary on what you did. Also include that you changed the API and that this is a breaking pull request 🙂 

Please make the title of the pull request more descriptive!

You need to adjust the tests, because currently your pull request breaks the build.

The following line must be reverted. The sidechain transaction have a different structure.  
```diff
-	trs.signature = crypto.signBytes(getDAppTransactionBytes(trs), keys)
+	trs.signatures.push(crypto.signBytes(getChainTransactionBytes(trs), keys))
```

Thanks 👍

**Comment by a1300** [comment]
@bassjobsen please adjust the Typescript definition file (`index.d.ts`) accordingly

Please remove the following line in `transactions/chains.js`. The `signatures` array is only available for Mainchain transactions.
```diff
+ signatures: []
```

Good work so far :+1:

**Comment by bassjobsen** [comment]
okay, i wil try to add that `index.d.ts` a.s.a.p, thanks!

**Comment by a1300** [comment]
## Review is Ok! :+1: 

## Breaking Changes
@sqfasd @liangpeili  This pull requests introduced a __BREAKING CHANGE__ and I would like to discuss this if its Ok to merge. 

The API interface changes from:  
- `aschJS.dapp.createDApp` -> `aschJS.chain.createChain`
- `aschJS.dapp.createInnerTransaction` -> `aschJS.chain.createInnerTransaction`

According to [**Semantic Versioning**](https://semver.org/) we would need to increase our __asch-js__ version number from `1.4.2` -> `2.0.0`. Or we could add a proxy file `dapp.js` that calls the new functions in `chain.js` and so  slowly deprecate the functions in  `dapp.js`. Then we only would need to upgrade version number from `1.4.2` -> `1.5.0`.

If we merge this code as it is it would break the following ASCH repos:  
- [asch-cli](https://github.com/AschPlatform/asch-cli)
- [asch-redeploy](https://github.com/aschplatform/asch-redeploy)
- Every DApp that uses the `dapp.createInnerTransaction` function will break
- Every DApp that uses the latest `master` branch from github (`https://github.com/AschPlatform/asch-js/tarball/master`)

@sqfasd , @liangpeili  what would be your preferred option?

**Comment by liangpeili** [comment]
@a1300  Can you fix this conflict?

**Comment by a1300** [comment]
@liangpeili yes, I will do that.

**Comment by a1300** [comment]
@liangpeili this PR is ready for merging :slightly_smiling_face:

**Pull request merged**
