### PR TITLE
Adjust to ASCH 1.4.2

### PR DESCRIPTION
**Pull request by a1300**
Dear @liangpeili,

this pull request makes the asch-js package compatible with the ASCH 1.4.2 release. The tests still break, but I will fix them with the next pull request.  

## What I've done
- I deleted the `lib/transactions/storage.js` file and also deleted its reference  in the `index.js` file  
- I updated the `lib/transactions/dapp.js` file  
- I updated the `lib/transactions/delegate.js` file  
- I updated the `lib/transactions/transaction.js` file and added the `unlock` function  
- I updated the `lib/transactions/transfer.js` file  
- I updated the `lib/transactions/uia.js` and removed the obsolete functions `createFlags` and `createAcl`  
- I updated the `lib/transactions/vote.js` file and added the `deleteVote` function  

## Packages where asch-js is used

Here I list all packages that are using asch-js today. This pull request shouldn't break them.

- [asch-cli](https://github.com/aschplatform/asch-cli) uses the latest asch-js package that was published on __npm__ `"asch-js": "*"`  
  - As we speak, asch-cli is already broken and not all options are working with the new ASCH 1.4.2 relaese. After this pull request was merged. @bassjobsen will fix the asch-cli package.
- [asch-core](https://github.com/aschplatform/asch-core) uses the latest asch-js release from __github__ `"asch-js": "https://github.com/AschPlatform/asch-js/tarball/v1.4.1",`
- [asch-frontend-2](https://github.com/AschPlatform/asch-frontend-2) uses the latest asch-js __npm__ release `"asch-js": "^1.3.10"` 
- [cctime-frontend](https://github.com/AschPlatform/cctime-frontend) uses the latest asch-js __npm__ release `"asch-js": "^1.3.10"`
- [asch-sandbox-dist](https://github.com/AschPlatform/asch-sandbox-dist) gets the asch-js version inherited from __asch-core__
  The sandbox is using only the following two function that don't change with this pull request:  

	`aschJS.transfer.createOutTransfer()` and `AschJS.transfer.signOutTransfer`

	File round.js
	```js
	// code omitted
	i = AschJS.transfer.createOutTransfer(app.meta.address, app.meta.name, a, t, r, n, s),

	// code omitted
	if (i.signatures.push(AschJS.transfer.signOutTransfer(i, g)), i.signatures.length >= app.meta.unlockNumber) break

	// code omitted
	var a = AschJS.transfer.signOutTransfer(out);
	```

----------

<br/>
<br/>

Please review my pull request. Is something missing for you?

All the best!
a1300

### CODE REVIEW

**Comment by bassjobsen** [comment]
Hi @a1300 thanks, you did a great job!
The the `username` parameter is remove from the `createDelegate` function at https://github.com/AschPlatform/asch-js/blob/6c1f7d0569484c18f48742ce27fd69b018d1e8e0/lib/transactions/delegate.js#L7.

On the other hand `registerDelegate()` in `asch-core` requires that the sender account has set a name already: https://github.com/AschPlatform/asch/blob/master/src/contract/basic.js#L330

As mention already at  https://github.com/AschPlatform/asch/issues/246 is is not clear what is expected? Should the sender register / set a name first?

**Comment by a1300** [comment]
> On the other hand `registerDelegate()` in `asch-core` requires that the sender account has set a name already

@bassjobsen yes, exactly
The ASCH 1.4.x transaction API doesn't need the username to register as a delegate (because the username must be already set).  
The _older_ API (ASCH 1.3.6) needed the username to register as a delegate

**Comment by bassjobsen** [comment]
@a1300 thanks for your quick reply:

> The ASCH 1.4.x transaction API doesn't need the username to register as a delegate (because the username must be already set).

Okay thanks, that's clear. Now i wonder shouldn't asch-js throw a error when the user name is not set? Or do you expect asch-core should handle this?

**Comment by a1300** [comment]
@bassjobsen NP 😃  
I think that the asch-js package isn't allowed to know if the username is set for an account (because it hasn't access to the database). asch-js is a simple reusable library package with no access to the blockchain database.

asch-core returns an error if the username is not set. I think that is good so 😃

**Comment by sqfasd** [comment]
Great job！

**Pull request merged**
